import React from "react";
import BarChart from "../charts/BarChart";
import PieChart from "../charts/PieChart";
import LineChart from "../charts/LineChart";
import AreaChart from "../charts/AreaChart";
import ColumnChart from "../charts/ColumnChart";
import StackColumnChart from "../charts/StackColumnChart";
import ColumnXChart from "../charts/ColumnXChart";

const tabDetails = {
  KPI: [
    {
      id: 1,
      title: "Experienced Index",
      width: 6,
      questionType: "Single_Select",
      chartType: "Area",
      variableName: "QA2",
      chartHeight: 220,
      valueRange: [],
      component: <AreaChart />,
    },
    {
      id: 2,
      title: "Overall Satisfaction",
      width: 6,
      questionType: "Single_Select",
      chartType: "ColumnX",
      variableName: "QA1",
      chartHeight: 220,
      valueRange: [],
      component: ColumnXChart,
    },
    {
      id: 3,
      title: "NPS",
      width: 6,
      questionType: "NPS",
      chartType: "Stack_Column",
      variableName: "QA2",
      chartHeight: 220,
      valueRange: [],
      component: <StackColumnChart />,
    },
    {
      id: 4,
      title: "Likely to Repurchase",
      width: 6,
      questionType: "Single_Select",
      chartType: "Column",
      variableName: "QA4",
      chartHeight: 220,
      valueRange: [],
      component: <ColumnChart />,
    },
  ],
  "Pre-Sales": [
    {
      id: 5,
      title: "Pre-Sales Satisfaction",
      width: 12,
      questionType: "Single_Select",
      chartType: "Column",
      variableName: "QPS2",
      chartHeight: 220,
      valueRange: [],
      component: <ColumnChart />,
    },
    {
      id: 6,
      title: "Experience with Website",
      width: 6,
      questionType: "Single_Select",
      chartType: "ColumnX",
      variableName: "QPS4",
      chartHeight: 220,
      valueRange: [],
      component: ColumnXChart,
    },
    {
      id: 7,
      title: "Availability of Dealer Staff for interaction",
      width: 6,
      questionType: "Single_Select",
      chartType: "Column",
      variableName: "QPS3",
      chartHeight: 220,
      valueRange: [],
      component: <AreaChart />,
    },
  ],
  Facility: [
    {
      id: 8,
      title: "Overall facilities/ Infrastructure",
      width: 4.7,
      questionType: "Single_Select",
      chartType: "Column",
      variableName: "QFI2",
      chartHeight: 220,
      valueRange: [],
      component: <AreaChart />,
    },
    {
      id: 9,
      title: "Promptness and reception",
      width: 4.7,
      questionType: "Multi_Select",
      chartType: "ColumnX",
      variableName: "T_QFI1_",
      chartHeight: 220,
      valueRange: [1],
      component: ColumnXChart,
    },
    {
      id: 10,
      title: "Showroom Ambience",
      width: 2.4,
      questionType: "Multi_Select",
      chartType: "Column",
      variableName: "T_QFI1_",
      valueRange: [2],
      chartHeight: 475,
      component: <BarChart />,
    },
    {
      id: 11,
      title: "Quality of offering refreshments",
      width: 4.7,
      questionType: "Multi_Select",
      chartType: "Column",
      variableName: "T_QFI1_",
      valueRange: [3],
      chartHeight: 220,
      component: <ColumnChart />,
    },
    {
      id: 12,
      title: "Ability to showcase the car model",
      width: 4.7,
      questionType: "Multi_Select",
      chartType: "Area",
      variableName: "T_QFI1_",
      valueRange: [4],
      chartHeight: 220,
      component: <AreaChart />,
    },
  ],
};

export default tabDetails;
